services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MK\MkScss\:
    resource: '../Classes/*'
  ScssPhp\ScssPhp\:
    resource: '../Vendor/scssphp-1.13.0/src/*'

  MK\MkScss\Backend\EventListener\CacheActionsEventListener:
    tags:
      - name: event.listener
        identifier: 'mk-scss/toolbar/cache-actions-event-listener'